service: tooltip-backend-v3

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: tooltip-backend-deployments-${aws:accountId}
    serverSideEncryption: AES256
  environment:
    NODE_ENV: production
    SUPABASE_URL: ${env:SUPABASE_URL, 'not-set'}
    SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY, 'not-set'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, 'not-set'}
  logs:
    restApi: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:TagResource
          Resource: "arn:aws:logs:*:*:*"

functions:
  api:
    handler: dist/lambda.handler
    timeout: 29
    memorySize: 1024
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0
