name: Trigger Amplify Build (root)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  trigger-amplify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI v2
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin

      - name: Trigger Amplify StartJob
        env:
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
          AMPLIFY_BRANCH_NAME: ${{ secrets.AMPLIFY_BRANCH_NAME }}
        run: |
          if [ -z "$AMPLIFY_APP_ID" ] || [ -z "$AMPLIFY_BRANCH_NAME" ]; then
            echo "AMPLIFY_APP_ID and AMPLIFY_BRANCH_NAME secrets are required"
            exit 1
          fi

          echo "Starting Amplify job for app: $AMPLIFY_APP_ID branch: $AMPLIFY_BRANCH_NAME"
          aws amplify start-job --app-id "$AMPLIFY_APP_ID" --branch-name "$AMPLIFY_BRANCH_NAME" --job-type RELEASE --job-parameters '{"sourceUrl":"https://github.com/${{ github.repository }}","sourceVersion":"${{ github.sha }}"}'
